### PR TITLE
Fix M1 Arm64 Macos builds by not specifying unrecognized flags

### LINKED ISSUE #1: MacOS M1 Arm64 Build Failure
Hello! I have found that running the command "dub build --build=release --arch=arm64-apple-macos" for this project yields the following error message:

```
    Starting Performing "release" build using ldc2 for aarch64, arm_hardfloat.
    Building semver 0.3.4: building configuration [library]
ldc2: Unknown command line argument '-preserve-dwarf-line-section=false'.  Try: 'ldc2 --help'
ldc2: Did you mean '--force-dwarf-frame-section=false'?
Error ldc2 failed with exit code 1.
```

Any idea on how to proceed past this point?

### PR DESCRIPTION
**Pull request by PierceLBrooks**
This fixes https://github.com/Inochi2D/gitver/issues/1

### CODE REVIEW

**Comment by LunaTheFoxgirl** [comment]
This should not be limited to x86_64 as some D compiler versions require it to be present to not fail the linking step for arm for newer SDK versions

**Comment by PierceLBrooks** [comment]
@LunaTheFoxgirl perhaps the recognition of this flag requires using beta M1 software ( e.g. Xcode ) ?

**Comment by LunaTheFoxgirl** [comment]
It appears that the issue is affecting the CI and my machines now as well. As such I've update the build script.

**Comment by PierceLBrooks** [comment]
https://github.com/Inochi2D/gitver/commit/f0faefe8a67db2acc93640692e6f1a4336e31b85 looks great! :)

**Pull request closed without merging**
